// <auto-generated />
namespace StudentManagementSystem.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class updateddate : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(updateddate));
        
        string IMigrationMetadata.Id
        {
            get { return "202504042132015_updateddate"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
